/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#01172b',
          hover: '#1a2e40',
          active: '#344555',
        },
        'on-primary': '#ffffff',
        secondary: {
          DEFAULT: '#1817e7',
          hover: '#1414c4',
        },
        tertiary: '#f2f93c',
        'on-tertiary': '#2b2d01',
        neutral: '#f2f3f4',
        outline: '#d9dcdf',
        background: '#ffffff',
        'on-background': 'rgba(0, 0, 0, 0.851)',
        'on-background-variant': 'rgba(0, 0, 0, 0.651)',
        surface: '#ffffff',
        'on-surface': 'rgba(0, 0, 0, 0.851)',
        'surface-variant': '#f2f3f4',
        error: {
          DEFAULT: '#d60808',
          hover: '#ba0707',
          active: '#9d0606',
          container: '#fff5f5',
        },
        'on-error': '#ffffff',
        'on-error-container': '#d60808',
        positive: {
          DEFAULT: '#009646',
          container: '#e6fdf0',
        },
        'on-positive-container': '#009646',
        warning: {
          DEFAULT: '#f26414',
          container: '#fef7f3',
        },
        'on-warning-container': '#f26414',
      },
      fontFamily: {
        sans: ['IBM Plex Sans Thai', 'sans-serif'],
      },
      fontSize: {
        display1: ['92px', { lineHeight: '102px', letterSpacing: '-0.64px', fontWeight: '400' }],
        display2: ['60px', { lineHeight: '70px', letterSpacing: '-0.64px', fontWeight: '400' }],
        display3: ['54px', { lineHeight: '64px', letterSpacing: '0px', fontWeight: '700' }],
        largeTitle: ['34px', { lineHeight: '41px', letterSpacing: '0.4px', fontWeight: '400' }],
        quotation1: ['42px', { lineHeight: '50px', letterSpacing: '0px', fontWeight: '400' }],
        title1: ['28px', { lineHeight: '34px', letterSpacing: '0.38px', fontWeight: '400' }],
        paragraph: ['28px', { lineHeight: '36px', letterSpacing: '0px', fontWeight: '400' }],
        quotation2: ['24px', { lineHeight: '30px', letterSpacing: '0px', fontWeight: '400' }],
        title2: ['22px', { lineHeight: '28px', letterSpacing: '-0.26px', fontWeight: '400' }],
        title3: ['20px', { lineHeight: '25px', letterSpacing: '-0.45px', fontWeight: '400' }],
        headline: ['17px', { lineHeight: '22px', letterSpacing: '-0.43px', fontWeight: '500' }],
        body: ['17px', { lineHeight: '22px', letterSpacing: '-0.43px', fontWeight: '400' }],
        callout: ['16px', { lineHeight: '21px', letterSpacing: '-0.31px', fontWeight: '400' }],
        subheadline: ['15px', { lineHeight: '20px', letterSpacing: '-0.23px', fontWeight: '400' }],
        footnote: ['13px', { lineHeight: '18px', letterSpacing: '-0.08px', fontWeight: '400' }],
        caption1: ['12px', { lineHeight: '16px', letterSpacing: '0px', fontWeight: '400' }],
        caption2: ['11px', { lineHeight: '13px', letterSpacing: '0.06px', fontWeight: '400' }],
      },
      borderRadius: {
        none: '0px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '32px',
        '3xl': '40px',
        '4xl': '48px',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '32px',
        xl: '40px',
        '2xl': '48px',
        '3xl': '64px',
        '4xl': '96px',
        '5xl': '128px',
      },
    },
  },
};
