/**
 * neonTheme — Finnomena's override fields for @coinbase/cds-web's
 * ThemeConfig, merged onto CDS's own defaultTheme at runtime by
 * ./createTheme.ts (see that file — ThemeProvider requires a FULL
 * ThemeConfig, and neonTheme here is deliberately partial).
 *
 * GENERATED FILE — do not hand-edit. Regenerate with:
 *   node scripts/sync-tokens.mjs && node scripts/generate-theme-config.mjs
 *
 * Source of truth: the raw Figma Token Studio export in ./tokens/*.json,
 * resolved by ./scripts/sync-tokens.mjs into ./tokens.resolved.json.
 *
 * STATUS (regenerated 2026-09-07T19:19:11.289Z):
 *
 *   ✅ space — all 15 of CDS's required step-keys ("0" through "10", plus
 *      "0.25"/"0.5"/"0.75") populated from tokens/size.json.
 *
 *   ✅ borderRadius — 9 of CDS's 11 step-keys ("0" through "800") populated
 *      from tokens/radius.json by value; "1000" (fully round) mapped by
 *      INTENT to Finnomena's "round" slug, not by literal number (CDS uses
 *      100000, Finnomena's export uses 200). "900" (56px) has no Finnomena
 *      equivalent and is left absent — CDS's defaultTheme value flows
 *      through for that one step at runtime.
 *
 *   ✅ fontFamily — fixed to "'IBM Plex Sans Thai', sans-serif" across all 13 CDS font
 *      roles (a confirmed decision, not the export's actual family name,
 *      "Finnomena Trek").
 *
 *   ⚠ fontSize / fontWeight / lineHeight — populated for ONLY the CDS font
 *      roles with an unambiguous same-name Finnomena counterpart:
 *      display1←"Display 1", display2←"Display 2", display3←"Display 3", title1←"Title 1", title2←"Title 2", title3←"Title 3", headline←"Headline", body←"Body".
 *      This is a first-pass, human-reviewable mapping (8 of 13 CDS roles) — title4/label1/label2/
 *      caption/legal have no confident Finnomena source and are left absent
 *      (CDS's defaultTheme values apply instead). fontSize/lineHeight are
 *      emitted as "Npx" strings (Finnomena's exact resolved pixel values —
 *      valid CSS; CDS's own defaultTheme uses rem, but px avoids inventing
 *      an unstated root-font-size assumption). fontWeight is converted from
 *      Finnomena's variant-name strings ("Regular","SemiBold",...) via the
 *      standard CSS numeric-weight convention, not Finnomena-specific data.
 *      
 *
 *   ⛔ COLOR — DELIBERATELY NOT POPULATED. lightSpectrum/darkSpectrum/
 *      lightColor/darkColor/lightIllustrationColor/darkIllustrationColor are
 *      not emitted at all. Finnomena's theme.json semantic names
 *      (text-primary, icon-on-brand, ...) share no vocabulary with CDS's
 *      semantic slugs (fg, bgPrimary, accentBoldBlue, ...) — mapping one
 *      onto the other is a real design decision, not a data-mapping
 *      problem, and this generator does not guess it. CDS's own default
 *      brand colors (Coinbase blue, etc.) render until a human fills in
 *      ./color-mapping.todo.md (also regenerated by this script) and this
 *      generator is extended to consume it. Do not tell a user their
 *      mockup's colors are on-brand until that's done.
 *
 *   Left entirely at CDS's default (confirmed: no Finnomena data exists for
 *   these at all — not a judgment call, nothing to draw from): iconSize,
 *   avatarSize, borderWidth (as a general scale — only scattered
 *   per-component stroke-weight overrides exist, not a real scale),
 *   controlSize, textTransform, shadow, fontFamilyMono.
 *
 * DO NOT hand-edit resolved values below without also updating
 * tokens/*.json and re-running the generator — this file should stay a
 * mechanical projection of the Figma export, not a second source of truth.
 */

// ---------------------------------------------------------------------------
// space — resolved from tokens/size.json, keyed to CDS's ThemeVars.Space.
// ---------------------------------------------------------------------------
export const space = {
  "0": 0,
  "1": 8,
  "2": 16,
  "3": 24,
  "4": 32,
  "5": 40,
  "6": 48,
  "7": 56,
  "8": 64,
  "9": 72,
  "10": 80,
  "0.25": 2,
  "0.5": 4,
  "0.75": 6,
  "1.5": 12,
} as const;

// ---------------------------------------------------------------------------
// borderRadius — resolved from tokens/radius.json, keyed to CDS's
// ThemeVars.BorderRadius. See file header for the "900" gap and the
// "round"→"1000" by-intent mapping.
// ---------------------------------------------------------------------------
export const borderRadius = {
  "0": 0,
  "100": 4,
  "200": 8,
  "300": 12,
  "400": 16,
  "500": 24,
  "600": 32,
  "700": 40,
  "800": 48,
  "1000": 100000,
} as const;

// ---------------------------------------------------------------------------
// Typography — flat per-role maps matching CDS's ThemeVars.FontFamily/
// FontSize/FontWeight/LineHeight (all alias the same 13 role keys). See
// file header for which roles have real Finnomena data vs. are left absent.
// ---------------------------------------------------------------------------
export const fontFamily = {
  display1: "'IBM Plex Sans Thai', sans-serif",
  display2: "'IBM Plex Sans Thai', sans-serif",
  display3: "'IBM Plex Sans Thai', sans-serif",
  title1: "'IBM Plex Sans Thai', sans-serif",
  title2: "'IBM Plex Sans Thai', sans-serif",
  title3: "'IBM Plex Sans Thai', sans-serif",
  title4: "'IBM Plex Sans Thai', sans-serif",
  headline: "'IBM Plex Sans Thai', sans-serif",
  body: "'IBM Plex Sans Thai', sans-serif",
  label1: "'IBM Plex Sans Thai', sans-serif",
  label2: "'IBM Plex Sans Thai', sans-serif",
  caption: "'IBM Plex Sans Thai', sans-serif",
  legal: "'IBM Plex Sans Thai', sans-serif",
} as const;

export const fontSize = {
  display1: "92px",
  display2: "60px",
  display3: "54px",
  title1: "28px",
  title2: "22px",
  title3: "20px",
  headline: "17px",
  body: "17px",
} as const;

export const fontWeight = {
  display1: "400",
  display2: "400",
  display3: "700",
  title1: "400",
  title2: "400",
  title3: "400",
  headline: "500",
  body: "400",
} as const;

export const lineHeight = {
  display1: "102px",
  display2: "70px",
  display3: "64px",
  title1: "34px",
  title2: "28px",
  title3: "25px",
  headline: "22px",
  body: "22px",
} as const;

/**
 * neonTheme — the partial ThemeConfig overrides every project merges onto
 * CDS's defaultTheme via ./createTheme.ts's createNeonTheme(). Deliberately
 * NOT typed as Partial<ThemeConfig> here — see that file for why, and for
 * where the real, complete ThemeConfig gets assembled.
 *
 * Custom tokens not already in CDS's ThemeVars must be declared via the
 * ThemeVarsExtended namespace before use — see the SKILL.md instructions
 * this file ships alongside.
 */
export const neonTheme = {
  space,
  borderRadius,
  fontFamily,
  fontSize,
  fontWeight,
  lineHeight,
};

export default neonTheme;
